cmake_minimum_required(VERSION 3.5)
project(roborts_planning)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake_module)
set(CMAKE_BUILD_TYPE Release)

find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_action REQUIRED)
find_package(tf2 REQUIRED)
find_package(tf2_ros REQUIRED)
find_package(tf2_geometry_msgs REQUIRED)
find_package(pcl_conversions REQUIRED)
find_package(nav_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(visualization_msgs REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(interactive_markers REQUIRED)
find_package(roborts_common REQUIRED)
find_package(roborts_msgs REQUIRED)
find_package(roborts_costmap REQUIRED)
find_package(ament_index_cpp REQUIRED)
find_package(tf2_eigen REQUIRED)

find_package(g2o REQUIRED CONFIG)
find_package(SUITESPARSE REQUIRED)
find_package(Eigen3 REQUIRED)
find_package(PCL REQUIRED)
find_package(ProtoBuf REQUIRED)
find_package(Boost REQUIRED)

add_subdirectory(global_planner)
add_subdirectory(local_planner)

ament_package()
